[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.1"
django-auth-exchange = "^0.1.2"
exchangelib = "^5.5.0"
black = "^24.10.0"
djangorestframework = "^3.15.2"
django-debug-toolbar = "^4.4.6"
django-extensions = "^3.2.3"
psycopg2 = "^2.9.10"


