# Generated by Django 5.1.1 on 2024-09-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={"ordering": ("id",), "verbose_name": "Women Item"},
        ),
    ]
