# Generated by Django 5.1.1 on 2024-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0002_alter_women_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="women",
            options={
                "ordering": ("id",),
                "verbose_name": "Women Item",
                "verbose_name_plural": "Women Items",
            },
        ),
    ]
