# Generated by Django 5.1.1 on 2024-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ews_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ewsitem",
            options={
                "ordering": ("-id",),
                "verbose_name": "EWS Item",
                "verbose_name_plural": "EWS Items",
            },
        ),
    ]
