# Generated by Django 5.1.1 on 2024-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ews_list", "0002_alter_ewsitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ewsitem",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
